# Java 6 estable en kernels modernos (Azul Zulu)
FROM azul/zulu-openjdk:6u119

# Maven 3.2.5 (última compatible con Java 6)
ADD https://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz /tmp/maven.tar.gz
RUN cd /tmp && \
    tar -xzf maven.tar.gz && \
    mv apache-maven-3.2.5 /opt/maven && \
    rm maven.tar.gz

ENV MAVEN_HOME=/opt/maven
ENV M2_HOME=/opt/maven
ENV PATH=$MAVEN_HOME/bin:$PATH

WORKDIR /work
EXPOSE 8080
CMD ["bash"]

# Mostrar versiones al construir
RUN java -version && mvn -version
